version: '3.8'
services:
  comfyui-worker:
    # Use your custom built image or build locally
    image: ${IMAGE_NAME:-szulic/comfyui-wan:latest-wan}
    build: 
      context: .
      target: final
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
      - enable_optimizations=true
      - download_480p_native_models=true
      - download_720p_native_models=false
      - download_vace=false
      - change_preview_method=true
    ports:
      - "8888:8888"  # Jupyter
      - "8188:8188"  # ComfyUI
      - "8189:8189"  # FastAPI ComfyUI Interface
    volumes:
      - ./data/comfyui/output:/workspace/ComfyUI/output
      - ./data/runpod-volume:/workspace
